name:                     Check cargo deny

on:
  pull_request:
  push:
    branches:
      - main
      - stable

jobs:
  cargo-deny:
    name:                 Cargo deny
    runs-on:              ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories

    continue-on-error:    ${{ matrix.checks == 'advisories' }}

    steps:
      - name:               Checkout Sources
        uses:               actions/checkout@v4.1.3

      - name:               Run cargo-deny
        uses:               EmbarkStudios/cargo-deny-action@v1
        with:
          command:          check ${{ matrix.checks }}

