version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["dependabot"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["dependabot-ci"]
    schedule:
      interval: "weekly"
