[package]
name = "kampela-ui-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
embedded-graphics-core = "0.3.3"
embedded-graphics-simulator = { version = "0.3.0" }
alloy-primitives = { version = "1.5.4" }
alloy-consensus = { version = "1.5.4" }
lazy_static = "1.4.0"
hex = "0.4.3"
clear-signing = { git = "ssh://git@github.com/Kalapaja/clear-signing.git", default-features = false, features = ["serde"] }
postcard = { version = "1.0", features = ["alloc"] }

kampela-ui = {path = "../"}
rand = { version = "0.8.5" }
